### ISSUE TITLE
full code release

### ISSUE THREAD

**Issue by LSQsjtu** [Aria-Zhangjl/E3-FaceNet#2]
Are the codes all released? I faced the error when running the sample.sh as follows:
ModuleNotFoundError: No module named 'training.networks_4_text'

It seems that the python file networks_4_text is missing?

When will the file used for text sampling be released?

**Comment by Aria-Zhangjl** [comment]
Hi, sorry for the delayed response. When doing the experiment, I used an informal name, 'networks_4_text', for the training script. However, when releasing the code, I renamed it to 'networks_4_E3_Face' to adhere to formal conventions. The saved model weights have stored the trained parameters along with the original code, including import statements. Consequently, an import error occurs when attempting to load the pretrained weights. I have rectified this issue, and the code should now function correctly.

Additionally, I have made a modification to the clip package. Specifically, I modified the model.py in the original clip script to enable simultaneous extraction of text features and token embeddings. To incorporate this change, please replace the existing model.py file in the clip installation path.

I sincerely apologize for any inconvenience caused by these mistakes.

**Comment by LSQsjtu** [comment]
Thank you for your response. However, the provided links for the new checkpoint only direct to a file. Could you please provide a direct link to access the new checkpoint?
